### ISSUE TITLE
分享中的此生天赋没有清空

### ISSUE THREAD

**Issue by duzzu** [xitu/coding-life#5]
分享中的此生天赋会继承每一次游戏选择的天赋
但效果并不会继承
![fcae8f2b109f66c024e1f9ae6331a2a](https://user-images.githubusercontent.com/36299597/134887774-d6bd5e74-c3f4-4ace-b3bd-b6bc448dc88b.png)
然后就是女装大佬的剧情线不够严谨
当出柜手术和老婆认为姐妹后
性别就判断为女了，
之后所有和自己配偶的互动都变成了老公
![878a54797161f28586bde1bc2255736](https://user-images.githubusercontent.com/36299597/134888086-5c48bd33-6eff-4c37-8d8f-2324530f343d.png)
![4c0580cb202998ce9c409ee094808b4](https://user-images.githubusercontent.com/36299597/134888095-79a983c6-2545-43cc-befc-24bf7e85783c.png)
![a813cb35db593b2a96ae7c2d94d8321](https://user-images.githubusercontent.com/36299597/134888108-a18787a3-46b1-4c15-a53b-29a4446773fc.png)
已发沸点，如果是bug坐等月影大佬给我抽个火眼金睛奖

**Comment by akira-cn** [comment]
这个应该已经修复了~
